# General settings for the Custom Fishing Rewards plugin
general:
  broadcast_on_rare_catch: true
  rare_broadcast_message: "{player} just caught a rare item: {item}!"

# Default fishing loot table
default_fishing_loot:
  - "COD:70:COMMON"          # Format: ITEM:CHANCE:RARITY
  - "PUFFERFISH:20:COMMON"
  - "TROPICAL_FISH:10:COMMON"

# Biome-specific loot tables
biomes:
  ocean:
    loot:
      - "TRIDENT:1:LEGENDARY"
      - "HEART_OF_THE_SEA:5:EPIC"
      - "TROPICAL_FISH:50:COMMON"
  plains:
    loot:
      - "IRON_INGOT:20:COMMON"
      - "DIAMOND:5:RARE"
      - "GOLD_INGOT:10:EPIC"
  swamp:
    loot:
      - "SLIME_BALL:30:COMMON"
      - "LILY_PAD:40:COMMON"
      - "MYSTIC_LILY_PAD:10:RARE"

# Rare event settings
events:
  KrakenEvent:
    chance: 5              # Chance (%) to trigger this event
    mob_spawn: "ELDER_GUARDIAN"
    message: "&cA Kraken has appeared! Fight it off!"
  BlessingEvent:
    chance: 10
    buffs:
      - "LUCK:300"         # Format: EFFECT:DURATION_IN_SECONDS
      - "SPEED:120"
    message: "&aYou feel the ocean's blessing! Luck and speed are on your side."

# Player statistics storage
stats: {}
