# FullFortune Plugin Configuration

# List of blocks that the Fortune effect applies to
# Add block names here that should drop extra items with the Fortune enchantment.
fortune-blocks:
  - DIAMOND_ORE
  - EMERALD_ORE
  - LAPIS_ORE
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE
  - COPPER_ORE
  - REDSTONE_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_REDSTONE_ORE

# Fortune levels above the standard maximum (optional)
# Allows Fortune enchantment to go beyond normal vanilla levels
max-fortune-level: 10

# Enable or disable auto-pickup for the drops
auto-pickup: true
