name: FullFortune
main: me.fullfortune.plugin.FullFortune
version: 1.0
api-version: 1.19
author: MrCappy
description: A plugin that applies Fortune to configured blocks with auto-pickup.

commands:
  fullfortune:
    description: Reloads the FullFortune plugin configuration.
    usage: /fullfortune reload
    permission: fullfortune.reload
    permission-message: You don't have permission to use this command!

permissions:
  fullfortune.reload:
    description: Allows the user to reload the FullFortune config.
    default: op
