name: CoinFlip
version: '1.0'
main: com.example.coinflip.CoinFlip
api-version: '1.21'
commands:
  coinflip:
    description: Play a CoinFlip game against another player.
    usage: /coinflip <player> <amount>
