name: VeinMiner
version: 1.0
main: com.example.veinminer.VeinMinerPlugin
api-version: 1.20
description: A plugin for automatic ore and log vein mining while holding SHIFT.
author: MrCappy
commands: {}
